Repository atmdrops/pydropsonde, pull requests merged in 2025-02, with the labels that each got.

#148 Remove unsorted
  pydropsonde/processor.py
Labels: Level_3

#154 add low physics p test
  pydropsonde/helper/quality.py
Labels: Level_2

#158 adapt dataset title to level
  pydropsonde/processor.py
Labels: Level_3, Level_2

#156 Bad gpsalt recovery
  pydropsonde/circles.py
  pydropsonde/helper/quality.py
  pydropsonde/pipeline.py
  pydropsonde/processor.py
Labels: Level_3

#174 remove broken sondes from l3
  pydropsonde/pipeline.py
  pydropsonde/processor.py
Labels: Level_3

#102 Concatenate and write Level 4
  .gitignore
  dropsonde.cfg
  example_data/HALO/Level_1/20200122/D20200122_151815QC.nc
  example_data/HALO/Level_1/20200122/D20200122_152307QC.nc
  pydropsonde/circles.py
  pydropsonde/helper/__init__.py
  pydropsonde/helper/xarray_helper.py
  pydropsonde/pipeline.py
  pydropsonde/processor.py
Labels: Level_4, important

#166 Fix l4
  pydropsonde/circles.py
Labels: Level_4

#176 rearrange history and global attribute addition
  dropsonde.cfg
  pydropsonde/helper/__init__.py
  pydropsonde/helper/paths.py
  pydropsonde/pipeline.py
  pydropsonde/processor.py
Labels: Level_3, Level_4, Level_2

#178 add description attribute to aircraft measurements
  pydropsonde/helper/__init__.py
Labels: Level_3, Level_2

#151 Add circle interpolation
  pydropsonde/circles.py
  pydropsonde/pipeline.py
Labels: Level_4

#183 correct density calculation and fix iwv to use mixing ratio
  pydropsonde/circles.py
  pydropsonde/helper/physics.py
Labels: Level_3, important
